/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/code-access`; params?: Router.UnknownInputParams; } | { pathname: `/dj-history`; params?: Router.UnknownInputParams; } | { pathname: `/dj`; params?: Router.UnknownInputParams; } | { pathname: `/grooms-add`; params?: Router.UnknownInputParams; } | { pathname: `/grooms-code-access`; params?: Router.UnknownInputParams; } | { pathname: `/grooms-list`; params?: Router.UnknownInputParams; } | { pathname: `/grooms-messages`; params?: Router.UnknownInputParams; } | { pathname: `/grooms`; params?: Router.UnknownInputParams; } | { pathname: `/guest-history`; params?: Router.UnknownInputParams; } | { pathname: `/guest`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/functionality.test`; params?: Router.UnknownInputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownInputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/code-access`; params?: Router.UnknownOutputParams; } | { pathname: `/dj-history`; params?: Router.UnknownOutputParams; } | { pathname: `/dj`; params?: Router.UnknownOutputParams; } | { pathname: `/grooms-add`; params?: Router.UnknownOutputParams; } | { pathname: `/grooms-code-access`; params?: Router.UnknownOutputParams; } | { pathname: `/grooms-list`; params?: Router.UnknownOutputParams; } | { pathname: `/grooms-messages`; params?: Router.UnknownOutputParams; } | { pathname: `/grooms`; params?: Router.UnknownOutputParams; } | { pathname: `/guest-history`; params?: Router.UnknownOutputParams; } | { pathname: `/guest`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/__tests__/functionality.test`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownOutputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/code-access${`?${string}` | `#${string}` | ''}` | `/dj-history${`?${string}` | `#${string}` | ''}` | `/dj${`?${string}` | `#${string}` | ''}` | `/grooms-add${`?${string}` | `#${string}` | ''}` | `/grooms-code-access${`?${string}` | `#${string}` | ''}` | `/grooms-list${`?${string}` | `#${string}` | ''}` | `/grooms-messages${`?${string}` | `#${string}` | ''}` | `/grooms${`?${string}` | `#${string}` | ''}` | `/guest-history${`?${string}` | `#${string}` | ''}` | `/guest${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/__tests__/functionality.test${`?${string}` | `#${string}` | ''}` | `/dev/theme-lab${`?${string}` | `#${string}` | ''}` | `/oauth/callback${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/code-access`; params?: Router.UnknownInputParams; } | { pathname: `/dj-history`; params?: Router.UnknownInputParams; } | { pathname: `/dj`; params?: Router.UnknownInputParams; } | { pathname: `/grooms-add`; params?: Router.UnknownInputParams; } | { pathname: `/grooms-code-access`; params?: Router.UnknownInputParams; } | { pathname: `/grooms-list`; params?: Router.UnknownInputParams; } | { pathname: `/grooms-messages`; params?: Router.UnknownInputParams; } | { pathname: `/grooms`; params?: Router.UnknownInputParams; } | { pathname: `/guest-history`; params?: Router.UnknownInputParams; } | { pathname: `/guest`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/__tests__/functionality.test`; params?: Router.UnknownInputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownInputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownInputParams; };
    }
  }
}
